apiVersion: v2
name: hello-container
description: A Helm chart for deploying ghcr.io/cooperj/hello-container
type: application
version: 1.2.2
appVersion: "1.2.1"   # renovate: datasource=docker depName=ghcr.io/cooperj/hello-container
home: https://github.com/cooperj/hello-container
sources: 
  - https://github.com/cooperj/hello-container
maintainers:
  - name: Josh Cooper
    email: hi@joshc.uk
    url: https://www.joshc.uk
